import type { TargetSpec } from '../types';

export const PATIENTS_TARGET: TargetSpec = {
  key:         'patients',
  label:       'מטופלות',
  description: 'ייבוא רשימת מטופלות חדשות עם פרטי קשר ופרטים אישיים.',
  tableName:   'patients',
  dedupeKeys:  ['full_name', 'phone'],
  fields: [
    { key: 'full_name', label: 'שם מלא',  required: true,  kind: 'string',
      aliases: ['name', 'שם', 'שם המטופלת'] },
    { key: 'phone',     label: 'טלפון',  kind: 'string',
      aliases: ['phone', 'נייד', 'טל'] },
    { key: 'email',     label: 'אימייל', kind: 'string',
      aliases: ['email', 'דואר אלקטרוני', 'מייל'] },
    { key: 'status',    label: 'סטטוס',  kind: 'enum',
      aliases: ['status'],
      enumValues: [
        { value: 'active',   labels: ['פעילה',     'active',   'פעיל'] },
        { value: 'inactive', labels: ['לא פעילה',  'inactive', 'לא פעיל'] },
        { value: 'waiting',  labels: ['ממתינה',    'waiting',  'בהמתנה'] },
      ],
    },
    { key: 'housing_type', label: 'סוג דירה', kind: 'enum',
      aliases: ['housing'],
      enumValues: [
        { value: 'independent',    labels: ['עצמאית', 'independent'] },
        { value: 'regular',        labels: ['רגילה',  'regular'] },
        { value: 'rehabilitation', labels: ['שיקומית', 'rehabilitation'] },
      ],
    },
    { key: 'apartment_address', label: 'כתובת דירה',  kind: 'string', aliases: ['apartment', 'דירה'] },
    { key: 'home_address',      label: 'כתובת מגורים', kind: 'string', aliases: ['home', 'מגורים'] },
    { key: 'father_name',       label: 'שם אבא',       kind: 'string', aliases: ['father'] },
    { key: 'mother_name',       label: 'שם אמא',       kind: 'string', aliases: ['mother'] },
    { key: 'family_position',   label: 'מקום במשפחה',  kind: 'string', aliases: ['position'] },
    { key: 'marital_status',    label: 'מצב משפחתי',   kind: 'enum',
      enumValues: [
        { value: 'single',   labels: ['רווקה',   'single']   },
        { value: 'married',  labels: ['נשואה',   'married']  },
        { value: 'divorced', labels: ['גרושה',   'divorced'] },
        { value: 'widowed',  labels: ['אלמנה',   'widowed']  },
      ],
    },
    { key: 'coordinator_id', label: 'רכזת', kind: 'lookup',
      aliases: ['coordinator', 'שם רכזת'],
      lookup: { table: 'staff', matchOn: 'full_name' },
      hint:   'שם הרכזת — תיפתר אוטומטית לפי טבלת הצוות.' },
    { key: 'staff_id', label: 'מטפלת', kind: 'lookup',
      aliases: ['therapist', 'שם מטפלת'],
      lookup: { table: 'staff', matchOn: 'full_name' },
      hint:   'שם המטפלת — תיפתר אוטומטית לפי טבלת הצוות.' },
    { key: 'notes', label: 'הערות', kind: 'string', aliases: ['notes', 'הערה'] },
  ],
};
