import type { TargetSpec } from '../types';

export const PAYMENTS_TARGET: TargetSpec = {
  key:         'payments',
  label:       'תשלומי שיראל',
  description: 'ייבוא רשומות תשלום חודשיות לרכזות.',
  tableName:   'payments',
  dedupeKeys:  ['coordinator_id', 'month'],
  fields: [
    { key: 'month', label: 'חודש', required: true, kind: 'string',
      aliases: ['month', 'חודש תשלום', 'תקופה'],
      hint: 'פורמט "YYYY-MM" או "מאי 2026".' },
    { key: 'amount', label: 'סכום', required: true, kind: 'number',
      aliases: ['amount', 'סכום בש״ח', 'סכום בש"ח', 'סכום לתשלום', 'סה"כ', 'total'] },
    { key: 'is_paid', label: 'שולם', kind: 'boolean',
      aliases: ['paid', 'שולם?', 'סטטוס תשלום', 'תשלום בוצע'],
      hint: '"כן"/"לא" / "true"/"false" / 1/0' },
    { key: 'payment_method', label: 'אמצעי תשלום', kind: 'enum',
      aliases: ['payment method', 'אמצעי', 'שיטת תשלום'],
      enumValues: [
        { value: 'bank_transfer', labels: ['העברה בנקאית', 'bank_transfer', 'העברה', 'bank transfer'] },
        { value: 'cash',          labels: ['מזומן', 'cash'] },
        { value: 'check',         labels: ['צ׳ק', 'צק', 'שיק', 'check', 'cheque'] },
        { value: 'other',         labels: ['אחר', 'אחרת', 'other'] },
      ],
    },
    { key: 'received_date', label: 'תאריך קבלה', kind: 'date',
      aliases: ['received', 'תאריך התשלום', 'תאריך'] },
    { key: 'coordinator_id', label: 'רכזת', kind: 'lookup',
      aliases: ['coordinator', 'שם רכזת', 'רכז', 'מרכזת'],
      lookup: { table: 'staff', matchOn: 'full_name' } },
    { key: 'email_status', label: 'סטטוס מייל', kind: 'enum',
      aliases: ['email status', 'סטטוס דוא״ל'],
      enumValues: [
        { value: 'not_sent', labels: ['לא נשלח', 'not_sent', 'not sent'] },
        { value: 'sent',     labels: ['נשלח', 'sent'] },
        { value: 'failed',   labels: ['כשל', 'failed'] },
      ],
    },
  ],
};
